### ISSUE TITLE
`dlv debug` fails with "could not launch process: stub exited while waiting for connection: exit status 0"

### ISSUE THREAD

**Issue by zeuslawyer** [derekparker/ultimate-go-debugging#1]
Hi Derek,

I'm doing this async and several weeks late as I'm based in Australia.  Ran my first ever `dlv debug` as per 1 hour and 12 mins in, on day 1, and the issue I'm getting is the same that this person got in [this SO post](https://stackoverflow.com/questions/73373686/could-not-launch-process-stub-exited-while-waiting-for-connection-exit-status)

I've commented on it too, because the suggested solution doesn't work for me.

**Note** This is only happening from the integrated VS Code Terminal.  From iTerm, the `dlv debug` command, run from inside `day1/cmds/debug/basic` does produce the dlv console prompt.

Have you seen this issue in your environment? My environment is:
```
❯ code -v
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
arm64

// and

❯ go version
go version go1.19 darwin/arm64

// and

Delve Debugger
Version: 1.9.0
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d $

```

**EXPECTED**
<img width="725" alt="Screen Shot 2022-08-19 at 12 11 04 am" src="https://user-images.githubusercontent.com/8016129/185416478-75837670-9d08-482e-a8bd-99decd1893d9.png">

**GOT**
```
❯ dlv debug                                                                                                                  
could not launch process: stub exited while waiting for connection: exit status 0
```

Thanks very much!

**Comment by zeuslawyer** [comment]
Update.

I was able to create the followingVSCode `launch.json` file and then use the inbuilt debugger to debug at breakpoints. 
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Package",
      "type": "go",
      "request": "launch",
      "mode": "auto",
      "program": "last-character.go",
      "args": ["arg1", "arg2", "arg3"]
    }
  ]
}
```

The debug console output below indicates that I'm using dlv dap -- so the headless server seems to be working.
```
Starting: /Users/zubinpratap/go_workspace/bin/dlv dap --check-go-version=false --listen=127.0.0.1:50820 --log-dest=3 from /Users/zubinpratap/Documents/myprojects/ardanlabs-go-debugging/day-1/cmds/debug/basic
DAP server listening at: 127.0.0.1:50820
Type 'dlv help' for list of commands.
Hello Gophers! Pass me a word and I will print the last character!
[/Users/zubinpratap/Documents/myprojects/ardanlabs-go-debugging/day-1/cmds/debug/basic/__debug_bin arg1 arg2 arg3]
The last character in that word is: 1
Process 68924 has exited with status 0
Detaching
dlv dap (68903) exited with code: 0
```

**Comment by zeuslawyer** [comment]
@derekparker  so some progress.  Turns out that if i run `arch -arch arm64 dlv debug` then it works in the VS Code integrated terminal.

Got the idea from: https://github.com/golang/vscode-go/issues/2391#issuecomment-1204800975

However, the rest of that thread indicates that it may be that my install is thinking its AMD...but I did a fresh re-install of everything to be ARM64. You can see that from my first post on this issue... `vscode` and `go` are both for ARM.


The only thing I can think of is that when I did the mac-to-mac transfer from my old machine to this M1, back in April, I must have dirtied some config.  I did that transfer and didn't even think about the AMD to ARM thing.  🤦🏻‍♂️. But i would've hoped that doing fresh installs of everything does the trick...apparently not?!

**Comment by derekparker** [comment]
Hey! Thanks for filing this issue, sorry for taking so long to get back to you had a busy week / weekend.

In any event, were you able to resolve the issue by ensuring the version of Delve being used by VS Code is built for the correct arch? Also, if this happened using the normal VSCode workflow (from installation to usage) it might be worth filing a bug against the VSCode Go plugin.

**Comment by zeuslawyer** [comment]
Hey @derekparker not at all man, thanks for taking the time to respond!

as far as I can tell, my vscode, and golang installs are all running arm64.  

If i use the integrated debugger in vscode things work fine (dlv dap, together with a launch.json)
but if i use the VScode integrated terminal then VScode seems to want me to prefix `dlv debug` with `arch -arch arm64 dlv debug`

That prefix is not necessary in my iterm though, so for now I'm following along in my iterm for the dlv CLI bits.

Yeah maybe I need to file a bug against the VSCode Go plugin.  Thank you for your reply!  And loving your teaching style.  
Thanks for putting the course together mate.

**Comment by derekparker** [comment]
> Hey @derekparker not at all man, thanks for taking the time to respond!
> 
> as far as I can tell, my vscode, and golang installs are all running arm64.
> 
> If i use the integrated debugger in vscode things work fine (dlv dap, together with a launch.json) but if i use the VScode integrated terminal then VScode seems to want me to prefix `dlv debug` with `arch -arch arm64 dlv debug`

Hmm. Is the output of `which dlv` different in the integrated terminal vs iTerm?

> That prefix is not necessary in my iterm though, so for now I'm following along in my iterm for the dlv CLI bits.
> 
> Yeah maybe I need to file a bug against the VSCode Go plugin. Thank you for your reply! And loving your teaching style. Thanks for putting the course together mate.

Yeah off the top of my head I can't think of what's causing it, I haven't run into this issue before. I'm happy to chime in on the VSCode issue you create, or help with any follow up questions you have. Also, thank you for the kind words I really appreciate it!

**Comment by zeuslawyer** [comment]
> Hmm. Is the output of which dlv different in the integrated terminal vs iTerm?
Nope! The same -- effectivelly `$GOPATH/bin/bin/dlv` on both.
